/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIProject;

/**
 *
 * @author HP
 */
public class background extends javax.swing.JFrame {

    /**
     * Creates new form background
     */
    public background() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        coin = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        GIFbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("OCR A Std", 1, 50)); // NOI18N
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIProject/image/tille1.gif"))); // NOI18N
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        Start.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 55)); // NOI18N
        Start.setText("START");
        Start.setBorder(null);
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 170, 100));

        Exit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 90, 40));

        coin.setForeground(new java.awt.Color(255, 255, 255));
        coin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIProject/image/gold-coin-splash-bingo-jackpot-win-casino-poker-coins-vector-d-background-realistic-golden-dollar-explosion-illustration-game-100250406.png"))); // NOI18N
        jPanel1.add(coin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIProject/image/19.event.sourcing.png"))); // NOI18N
        money.setText("jLabel1");
        jPanel1.add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        GIFbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIProject/image/16DCbx.gif"))); // NOI18N
        GIFbackground.setText("jLabel1");
        jPanel1.add(GIFbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        this.setVisible(false);
        question1.help = 3;
        new question1().setVisible(true);
    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new background().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel GIFbackground;
    private javax.swing.JButton Start;
    private javax.swing.JLabel coin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel money;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
