/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIProject;

import static GUIProject.question1.callquestion;
import java.util.ArrayList;
import java.util.List;

/**
 * This class has three buttons which are "back", "skip", and "hint". 
 * Choose the choices you want and back to the previous class.
 * 
 * @author Vichaphol Thamsuthikul and Chawanant Kerdchuen
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form HelpJFrame
     */
    private int count = 1;
    question1 q = new question1();
    public List<String> hint = new ArrayList<>();

    public Help() {
        initComponents();
         q.init("src//GUIProject//QandA/Hint.TXT", hint);
        Hint.setVisible(false);
        this.count = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        HintB = new javax.swing.JButton();
        Skip = new javax.swing.JButton();
        Hint = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        HintB.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        HintB.setText("HINT");
        HintB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintBActionPerformed(evt);
            }
        });
        jPanel1.add(HintB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 180, 100));

        Skip.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        Skip.setText("SKIP");
        Skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipActionPerformed(evt);
            }
        });
        jPanel1.add(Skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 180, 90));

        Hint.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Hint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintActionPerformed(evt);
            }
        });
        jPanel1.add(Hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 800, 160));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIProject/image/8bitflyingmoney.gif"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(530, 180, 818, 647);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        q.setVisible(true);
        this.setVisible(false);
        q.clickCount = 1;
        q.setCount();
        q.setSaveQuestion();
        q.setImagePrice();
    }//GEN-LAST:event_BackActionPerformed

    private void HintBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintBActionPerformed
        if (count == 1) {
            Hint.setVisible(true);
            Hint.setText(hint.get(callquestion));
            count = 0;
            q.clickCount = 1;
        }


    }//GEN-LAST:event_HintBActionPerformed

    private void SkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipActionPerformed
        if (count == 1) {
            q.setVisible(true);
            this.setVisible(false);
            q.runNextButt();
            q.setImagePrice();
            count = 0;
        }
        q.clickCount = 1;
        q.setCount();
    }//GEN-LAST:event_SkipActionPerformed

    private void HintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Hint;
    private javax.swing.JButton HintB;
    private javax.swing.JButton Skip;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
